portal:
  image: nginx
  ports:
   - "8080:80"
  volumes:
   - /Users/diego/Sources/docker-cluster/cluster/default.conf:/etc/nginx/conf.d/default.conf
  links:
   - tomcatOne:tomcat1
   - tomcatTwo:tomcat2
   - tomcatThree:tomcat3
tomcatOne:
  image: tomcat
  volumes:
   - /Users/diego/Sources/docker-cluster/cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - /Users/diego/Sources/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - /Users/diego/Sources/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
tomcatTwo:
  image: tomcat
  volumes:
   - /Users/diego/Sources/docker-cluster/cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - /Users/diego/Sources/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - /Users/diego/Sources/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
tomcatThree:
  image: tomcat
  volumes:
   - /Users/diego/Sources/docker-cluster/cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - /Users/diego/Sources/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - /Users/diego/Sources/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml


